name: build

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ mingw, mswin ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
    - name: git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global advice.detachedHead 0
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        rubygems: ${{ matrix.ruby < '2.7' && '3.4.22' || '' }}
        bundler-cache: true
    - name: Run test
      run: bundle exec rake compile test
